name: AdventureTools
version: 1.1
author: Wings
main: me.nexusnetwork.adventuretools.AdventureTools
api-version: 1.16
commands:
  gmsg:
    description: Game Masters talk to players as a higher power
    usage: /gmsg <target player or @a> <message>
    permission: adventuretools.gmsg
  lightning:
    description: Summons lightning where you are looking
    usage: /lightning to obtain a lightning rod
    permission: adventuretools.lt
  offlinetp:
    description: tps to a offline player
    usage: /offlinetp [target]
    permission: adventuretools.otp